controllers/administradoraController.php
<?
namespace app\controllers;

use app\components\maskComponent;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\AdministradoraModel;
use Yii;
use yii\db\Command;

class AdministradoraController extends Controller{
    public function actionListaAdministradora(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }


        $query = AdministradoraModel::find();

        $paginacao = new Pagination([
            'defaultPageSize'=> 5,
            'totalCount'=> $query->count(),
        ]);

        $administradora = $query->orderBy('nomeAdm')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('lista-administradora', [
            'administradora'=> $administradora,
            'paginacao'=>$paginacao,
        ]);
    }

    public function actionFiltroAdministradora(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;

        $query = AdministradoraModel::find()
        ->where(['like', 'nomeAdm', $request->get('termo1')]);

        $paginacao = new Pagination([
            'defaultPageSize'=> 5,
            'totalCount'=> $query->count(),
        ]);

        $administradora = $query->orderBy('nomeAdm')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('lista-administradora', [
            'administradora'=> $administradora,
            'paginacao'=>$paginacao,
        ]);
        


        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $unidade = $query->orderBy('numero')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();


        return $this->render('lista-unidade',[
            'unidade'=>$unidade,
            'paginacao'=>$paginacao,
        ]);
    }

    public static function listaAdministradoraSelect(){
        $query = AdministradoraModel::find();

        return $query->orderBy('nomeAdm')->all();
    }

    public function actionCadastroAdministradora(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        return $this->render('cadastro-administradora');
    }

    public function actionRealizaCadastroAdministradora(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new AdministradoraModel();
            foreach ($request->post() as $ch => $value) {
                if($ch == 'cnpj'){
                    $getMani[$ch] = maskComponent::desMask($value);
                }else{
                    $getMani[$ch] = $value;
                }
            }
            $model->attributes = $getMani;
            $model->save();
            return $this->redirect(['administradora/lista-administradora']);
        }

        return $this->render('cadastro-administradora');
    }

    public function actionEditarAdministradora(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = AdministradoraModel::find();
            $administradora = $query->where(['id' => $request->get()])->one();
        }
        
        return $this->render('editar-administradora',[
            'edit' => $administradora
        ]);
    }
    public function actionRealizaEdicaoAdministradora(){
        $request = \yii::$app->request;
        
        if($request->isPost){
            $model = AdministradoraModel::findOne($request->post('id'));
            foreach ($request->post() as $ch => $value) {
                if($ch == 'cnpj'){
                    $getMani[$ch] = maskComponent::desMask($value);
                }else{
                    $getMani[$ch] = $value;
                }
            }
            $model->attributes = $getMani;

            if($model->update()){
                return $this->redirect(['administradora/lista-administradora']);
            }else{
                return $this->redirect(['administradora/lista-administradora', 'msg' => 'erro']);
            }
        }
    }
    public function actionDeletaAdministradora(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        try {
            $request = \yii::$app->request;
            if($request->isGet){
                $model = AdministradoraModel::findOne($request->get('id'));
                if($model->delete()){
                    return $this->redirect(['administradora/lista-administradora',
                        'myAlert' => [
                            'type' => 'success',
                            'msg' => 'Registro Deletado',
                            'redir' => 'index.php?r=administradora/lista-administradora'
                        ]
                    ]);
                }
                
            } 
        }catch (\Throwable $th) {         
            return $this->redirect(['administradora/lista-administradora',
            'myAlert' => [
                'type' => 'danger',
                'msg' => 'Registro não Deletado',
                'redir' => 'index.php?r=administradora/lista-administradora'
                ]
            ]);
        }
    }

    public static function totaladm(){
        $query = \yii::$app->db->createCommand('
        select
        count(id)
        from administradora 
        ')->queryScalar();
        return $query;
    }

    public static function listaContobyAdm(){
        $query = \yii::$app->db->createCommand('
        select
        nomeAdm,
        count(cond.nomeCondominio) as totalcond
        from administradora
        inner join condominio cond on cond.idAdm = administradora.id
        group by nomeAdm
        order by nomeAdm
        ')->queryAll();

        return $query;
    }
}
?>

views/administradora/cadastro-administradora.php
<?
use yii\helpers\Url;
?>
<h1 class="text-center mb-5 text-light">Cadastro de Administradora</h1>
<form action="<?= Url::to(['administradora/realiza-cadastro-administradora'])?>" class="formAdm" id="cadastroAdministradora" method="POST">
    <div class="form-row">
      <div class="form-group col-md-2">
        <input type="text" class="form-control" name="nomeAdm" value="" placeholder="Nome da Administradora" required>
      </div>
        <div class="form-group col-md-2">
      <input type="text" class="form-control" name="cnpj" value="" placeholder="CNPJ" required>
        </div>
    </div>
    <div class="form-group">
       <input type="hidden" name="<?=\yii::$app->request->csrfParam; ?>" value="<?=\yii::$app->request->csrfToken;?>"> 
    </div>
  <button type="submit" class="btn btn-primary buttonEnviar">Enviar</button>
</form>

views/administradora/editar-administradora.php
<?
use yii\helpers\Url;
?>
<form action="<?= Url::to(['administradora/realiza-edicao-administradora'])?>" class="formAdm" id="cadastroAdministradora" method="POST">
    <div class="form-row">
      <div class="form-group col-md-2">
        <input type="text" class="form-control" name="nomeAdm" value="<?=$edit['nomeAdm']?>" placeholder="Nome da Administradora" required>
      </div>
        <div class="form-group col-md-2">
      <input type="text" class="form-control" name="cnpj" value="<?=$edit['cnpj']?>" placeholder="CNPJ" required>
        </div>
    </div>
    <div class="form-group">
      <input type="hidden" name="id" value="<?=$edit['id']?>">
       <input type="hidden" name="<?=\yii::$app->request->csrfParam; ?>" value="<?=\yii::$app->request->csrfToken;?>"> 
    </div>
  <button type="submit" class="btn btn-primary buttonEnviar">Enviar</button>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
</form>

views/administradora/lista-administradora.php
<?

use app\components\alertComponent;
use app\components\maskComponent;
use app\components\modalComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;

global $urlSite;
if(isset($_GET['myAlert'])){

    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}
?>
<h1 class="text-center">Lista Administradora</h1>

<table class="table table-striped table-hover table-bordered table-dark" id="listaAdm">
    <tr>
            <td colspan="10">
            <form class="form-inline my-2 my-lg-0" id="filtro" method="GET">
                <input type="hidden" name="r" value="administradora/filtro-administradora">
                <input class="form-control mr-sm-2 termo1" type="search" placeholder="busca por nome" aria-label="Search" name="termo1">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit" >Buscar</button>
                <a class="btn btn-outline-danger my-2 my-sm-0 ml-3" href="<?=$urlSite?>?r=administradora/lista-administradora">Limpar</a>
            </form>
            </td>
        </tr>
        <tr>
            <td scope="col" class="text-center">Nome</td>
            <td scope="col" class="text-center">CNPJ</td>
            <td scope="col" class="text-center">Data</td>
            <td class="text-center"><a href="<?=$urlSite?>?r=administradora/cadastro-administradora" class="btn btn-light px-3 py-0"><small class="mr-2">Adicionar</small><i class="bi bi-plus-circle"></i></a></td>
        </tr>
        <?
        foreach($administradora as $ch2=>$dados){
        ?>
        <tr data-id="<?=$dados['id']?>">
            <td class="text-center"><?=$dados['nomeAdm']?></td>
            <td class="text-center"><?=maskComponent::mask($dados['cnpj'],'cnpj')?></td>
            <td class="text-center"><?=$dados['dataCadastro']?></td>
            <td class="text-center">
                <a href="<?=$urlSite?>?r=administradora/deleta-administradora&id=" data-id="<?=$dados['id']?>" class="removerAdm text-white mr-5"><i class="bi bi-trash3"></i></a>
                <a href="<?=$urlSite?>?r=administradora/editar-administradora&id=<?=$dados['id']?>" class=" text-white openModal"><i class="bi bi-pencil-square"></i></a>
            </td>
        </tr>
        <? } ?>
        <tr>
            <td colspan="10" class="text-right">Total Registros <small class="badge badge-light totalRegistro"><?=$paginacao->totalCount?></small></td>
        </tr>
    </table>
    <div class="row">
    <div class="col-md-12 mb-5">
        <?= LinkPager::widget(
            [
                'pagination' => $paginacao,
                'linkContainerOptions' =>[
                    'class' => 'page-item'
                ],
                'linkOptions' => [
                    'class' => 'page-link'
                ],
                'disabledListItemSubTagOptions' => [
                    'class' => 'page-link'
                ]
                ]) 
        ?>
    </div>
</div>
<?=modalComponent::modal()?>