controllers/conselhoController.php
<?
namespace app\controllers;

use app\models\CondominioModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\ConselhoModel;
use Yii;

class ConselhoController extends Controller{
    public function actionListaConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }



        $query = (new \yii\db\Query())
        ->select('con.id,
        con.idCondominio,
        cond.nomeCondominio,
        con.nome,
        con.funcao
        ')
        ->from(ConselhoModel::tableName().' con')
        ->innerJoin(CondominioModel::tableName().' cond','cond.id = con.idCondominio');

        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $conselho = $query->orderBy('nome')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('lista-conselho',[
            'conselho'=>$conselho,
            'paginacao'=>$paginacao, 
        ]);
    }

    public function actionFiltroConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;

        $query = (new \yii\db\Query())
        ->select('
        con.id,
        con.idCondominio,
        cond.nomeCondominio,
        con.nome,
        con.funcao
        ')
        ->from(ConselhoModel::tableName().' con')
        ->innerJoin(CondominioModel::tableName().' cond','cond.id = con.idCondominio')
        ->where(['like', 'con.nome', $request->get('termo1')])
        ->andWhere(['like', 'cond.nomeCondominio', $request->get('termo2')]);


        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $conselho = $query->orderBy('nome')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();


        return $this->render('lista-conselho',[
            'conselho'=>$conselho,
            'paginacao'=>$paginacao,
        ]);
    }

    public function actionCadastroConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        return $this->render('cadastro-conselho');
    }

    public function actionRealizaCadastroConselho(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new ConselhoModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['conselho/lista-conselho']);
        }

        return $this->render('cadastro-conselho');
    }

    public function actionEditarConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = ConselhoModel::find();
            $conselho = $query->where(['id' => $request->get()])->one();
        }
        
        return $this->render('editar-conselho',[
            'edit' => $conselho
        ]);
    }
    public function actionRealizaEdicaoConselho(){
        $request = \yii::$app->request;
        
        if($request->isPost){
            $model = ConselhoModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            if($model->update()){
                return $this->redirect(['conselho/lista-conselho']);
            }else{
                return $this->redirect(['conselho/lista-conselho', 'msg' => 'erro']);
            }
        }
    }
    public function actionDeletaConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        try {
            $request = \yii::$app->request;
            if($request->isGet){
                $model = ConselhoModel::findOne($request->get('id'));
                if($model->delete()){
                    return $this->redirect(['conselho/lista-conselho',
                        'myAlert' => [
                            'type' => 'success',
                            'msg' => 'Registro Deletado',
                            'redir' => 'index.php?r=conselho/lista-conselho'
                        ]
                    ]);
                }
                
            } 
        }catch (\Throwable $th) {         
            return $this->redirect(['conselho/lista-conselho',
            '   myAlert' => [
                'ty pe' => 'danger',
                'msg    ' => 'Registro não Deletado',
                'redir' => 'index.php?r=conselho/lista-conselho'
                ]
            ]   );
        }
    }
}
?>

views/conselho/cadastro-conselho.php
<?
use app\controllers\CondominioController;
use yii\helpers\Url;
?>
<h1 class="text-center mb-5 text-light">Cadastro de Conselho</h1>
<form action="<?=Url::to(['conselho/realiza-cadastro-conselho'])?>" class="formConselho" method="POST">
  <div class="form-row">
  <div class="form-group col-md-3">
        <select id="inputState" class="form-control" name="idCondominio">
          <option selected>condominio</option>
          <?foreach(CondominioController::listaCondominioSelect() as $condo){?>
            <option value="<?=$condo['id']?>"><?=$condo['nomeCondominio']?></option>
          <?}?>
        </select>
    </div>
    <div class="form-group col-md-2">
        <input type="text" class="form-control" name="nome" value="" placeholder="nome">
    </div>
    <div class="form-group col-md-3">
        <select id="inputState" class="form-control" name="funcao">
          <option selected>função</option>
          <option value="sindico">sindico</option>
          <option value="subsindico">subSindico</option>
          <option value="conselheiro">conselheiro</option>
        </select>
    </div>
  <div class="form-group">
            <input type="hidden" name="<?=\yii::$app->request->csrfParam; ?>" value="<?=\yii::$app->request->csrfToken;?>">
    </div>
  <button type="submit" class="btn btn-primary buttonEnviar">Enviar</button>
</form>

views/conselho/editar-conselho.php
<?

use app\components\selectedComponent;
use app\controllers\CondominioController;
use yii\helpers\Url;
?>
<form action="<?=Url::to(['conselho/realiza-edicao-conselho'])?>" class="formConselho" method="POST">
  <div class="form-row">
  <div class="form-group col-md-3">
        <select id="inputState" class="form-control" name="idCondominio">
          <option selected>condominio</option>
          <?foreach(CondominioController::listaCondominioSelect() as $condo){?>
            <option value="<?=$condo['id']?>" <?=selectedComponent::isSelected($condo['id'],$edit['idCondominio'])?>><?=$condo['nomeCondominio']?></option>
          <?}?>
        </select>
    </div>
    <div class="form-group col-md-2">
        <input type="text" class="form-control" name="nome" value="<?=$edit['nome']?>" placeholder="nome">
    </div>
    <div class="form-group col-md-3">
        <select id="inputState" class="form-control" name="funcao">
          <option selected>função</option>
          <option value="sindico">sindico</option>
          <option value="subsindico">subSindico</option>
          <option value="conselheiro">conselheiro</option>
        </select>
    </div>
  <div class="form-group">
    <input type="hidden" name="id" value="<?=$edit['id']?>">
    <input type="hidden" name="<?=\yii::$app->request->csrfParam; ?>" value="<?=\yii::$app->request->csrfToken;?>">
  </div>
  <button type="submit" class="btn btn-primary buttonEnviar">Enviar</button>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
</form>

views/conselho/lista-conselho.php
<?

use app\components\alertComponent;
use app\components\filtroComponent;
use app\components\modalComponent;
use app\controllers\CondominioController;
use yii\helpers\Html;
use yii\widgets\LinkPager;

global $urlSite;
if(isset($_GET['myAlert'])){

    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}
?>
<h1 class="text-center">Lista Conselho</h1>
 <table class="table table-striped table-hover table-bordered table-dark" id="listaConselho">
    <tr>
            <td colspan="10">
            <?=filtroComponent::filtro('conselho','filtro-conselho','nome','condominio',CondominioController::listaCondominioSelect(), 'nomeCondominio')?>
            </td>
        </tr>
        <tr>
            <td scope="col" class="text-center">Condominio</td>
            <td scope="col" class="text-center">Nome</td>
            <td scope="col" class="text-center">funcao</td>
            <td class="text-center"><a href="<?=$urlSite?>?r=conselho/cadastro-conselho" class="btn btn-light px-3 py-0"><small class="mr-2">Adicionar</small><i class="bi bi-plus-circle"></i></a></td>
        </tr>
        <?
        foreach($conselho as $ch2=>$dados){
        ?>
        <tr data-id="<?=$dados['id']?>">
            <td class="text-center"><?=$dados['nomeCondominio']?></td>
            <td class="text-center"><?=$dados['nome']?></td>
            <td class="text-center"><?=$dados['funcao']?></td>
            <td class="text-center">
                <a href="<?=$urlSite?>?r=conselho/deleta-conselho&id=<?=$dados['id']?>" data-id="<?=$dados['id']?>" class="removerConselho text-white mr-5"><i class="bi bi-trash3"></i></a>
                <a href="<?=$urlSite?>?r=conselho/editar-conselho&id=<?=$dados['id']?>" class=" text-white openModal"><i class="bi bi-pencil-square"></i></a>
            </td>
        </tr>
        <? } ?>
        <tr>
            <td colspan="10" class="text-right">Total Registros <small class="badge badge-light totalRegistro"><?=$paginacao->totalCount?></small></td>
        </tr>


     </table> 
     <div class="row">
    <div class="col-md-12 mb-5">
        <?= LinkPager::widget(
            [
                'pagination' => $paginacao,
                'linkContainerOptions' =>[
                    'class' => 'page-item'
                ],
                'linkOptions' => [
                    'class' => 'page-link'
                ],
                'disabledListItemSubTagOptions' => [
                    'class' => 'page-link'
                ]
                ]) 
        ?>
    </div>
</div>
<?=modalComponent::modal()?>