controllers/blocoController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocoModel;
use app\models\CondominioModel;
use Yii;

class BlocoController extends Controller{
    public function actionListaBloco(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }



        $query = (new \yii\db\Query())
        ->select('
        b.id,
        b.idCondominio,
        b.nomeBloco,
        b.qtAndar,
        b.qtAptoAndar,
        cond.nomeCondominio
        ')
        ->from(BlocoModel::tableName().' b')
        ->innerJoin(CondominioModel::tableName().' cond', 'cond.id = b.idCondominio');

        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $bloco = $query->orderBy('nomeBloco')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();


        return $this->render('lista-bloco',[
            'bloco'=>$bloco,
            'paginacao'=>$paginacao,
        ]);
    }

    public function actionFiltroBloco(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;

        $query = (new \yii\db\Query())
        ->select('
        b.id,
        b.idCondominio,
        b.nomeBloco,
        b.qtAndar,
        b.qtAptoAndar,
        cond.nomeCondominio
        ')
        ->from(BlocoModel::tableName().' b')
        ->innerJoin(CondominioModel::tableName().' cond','cond.id = b.idCondominio')
        ->where(['like', 'b.nomeBloco', $request->get('termo1')])
        ->andWhere(['like', 'cond.nomeCondominio', $request->get('termo2')]);


        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $bloco = $query->orderBy('nomeBloco')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();


        return $this->render('lista-bloco',[
            'bloco'=>$bloco,
            'paginacao'=>$paginacao,
        ]);
    }

    public static function listaBlocoSelect(){
        $query = BlocoModel::find();
        return $query->orderBy('nomeBloco')->all();
    }

    public static function listaBlocoSelectEdit($from){
        $query = BlocoModel::find();
        $data = $query->where(['idCondominio' => $from])->orderBy('nomeBloco')->all();
        return $data;
    }

    public function actionCadastroBloco(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        return $this->render('cadastro-bloco');
    }

    public function actionRealizaCadastroBloco(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new BlocoModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['bloco/lista-bloco']);
        }

        return $this->render('cadastro-bloco');
    }

    public function actionListaBlocoApi(){
        $request = \yii::$app->request;
        $query = BlocoModel::find();
        $data = $query->where(['idCondominio' => $request->post()])->orderBy('nomeBloco')->all();

        $dados = array();
        $i=0;
        foreach($data as $d){
        $dados[$i]['id'] = $d['id'];
        $dados[$i]['nomeBloco'] = $d['nomeBloco'];
        $i++;
        }
        echo json_encode($dados);

        
    }

    public function actionEditarBloco(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = BlocoModel::find();
            $bloco = $query->where(['id' => $request->get()])->one();
        }
        
        return $this->render('editar-bloco',[
            'edit' => $bloco
        ]);
    }
    public function actionRealizaEdicaoBloco(){
        $request = \yii::$app->request;
        
        if($request->isPost){
            $model = BlocoModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            if($model->update()){
                return $this->redirect(['bloco/lista-bloco']);
            }else{
                return $this->redirect(['bloco/lista-bloco', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaBloco(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        try {
            $request = \yii::$app->request;
            if($request->isGet){
                $model = BlocoModel::findOne($request->get('id'));
                if($model->delete()){
                    return $this->redirect(['bloco/lista-bloco',
                        'myAlert' => [
                            'type' => 'success',
                            'msg' => 'Registro Deletado',
                            'redir' => 'index.php?r=bloco/lista-bloco'
                        ]
                    ]);
                }
                
            } 
        }catch (\Throwable $th) {         
            return $this->redirect(['bloco/lista-bloco',
            'myAlert' => [
                'type' => 'danger',
                'msg' => 'Registro não Deletado',
                'redir' => 'index.php?r=bloco/lista-bloco'
                ]
            ]   );
        }
    }
}
?>

controllers/conselhoController.php
<?
namespace app\controllers;

use app\models\CondominioModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\ConselhoModel;
use Yii;

class ConselhoController extends Controller{
    public function actionListaConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }



        $query = (new \yii\db\Query())
        ->select('con.id,
        con.idCondominio,
        cond.nomeCondominio,
        con.nome,
        con.funcao
        ')
        ->from(ConselhoModel::tableName().' con')
        ->innerJoin(CondominioModel::tableName().' cond','cond.id = con.idCondominio');

        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $conselho = $query->orderBy('nome')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('lista-conselho',[
            'conselho'=>$conselho,
            'paginacao'=>$paginacao, 
        ]);
    }

    public function actionFiltroConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;

        $query = (new \yii\db\Query())
        ->select('
        con.id,
        con.idCondominio,
        cond.nomeCondominio,
        con.nome,
        con.funcao
        ')
        ->from(ConselhoModel::tableName().' con')
        ->innerJoin(CondominioModel::tableName().' cond','cond.id = con.idCondominio')
        ->where(['like', 'con.nome', $request->get('termo1')])
        ->andWhere(['like', 'cond.nomeCondominio', $request->get('termo2')]);


        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $conselho = $query->orderBy('nome')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();


        return $this->render('lista-conselho',[
            'conselho'=>$conselho,
            'paginacao'=>$paginacao,
        ]);
    }

    public function actionCadastroConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        return $this->render('cadastro-conselho');
    }

    public function actionRealizaCadastroConselho(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new ConselhoModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['conselho/lista-conselho']);
        }

        return $this->render('cadastro-conselho');
    }

    public function actionEditarConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = ConselhoModel::find();
            $conselho = $query->where(['id' => $request->get()])->one();
        }
        
        return $this->render('editar-conselho',[
            'edit' => $conselho
        ]);
    }
    public function actionRealizaEdicaoConselho(){
        $request = \yii::$app->request;
        
        if($request->isPost){
            $model = ConselhoModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            if($model->update()){
                return $this->redirect(['conselho/lista-conselho']);
            }else{
                return $this->redirect(['conselho/lista-conselho', 'msg' => 'erro']);
            }
        }
    }
    public function actionDeletaConselho(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        try {
            $request = \yii::$app->request;
            if($request->isGet){
                $model = ConselhoModel::findOne($request->get('id'));
                if($model->delete()){
                    return $this->redirect(['conselho/lista-conselho',
                        'myAlert' => [
                            'type' => 'success',
                            'msg' => 'Registro Deletado',
                            'redir' => 'index.php?r=conselho/lista-conselho'
                        ]
                    ]);
                }
                
            } 
        }catch (\Throwable $th) {         
            return $this->redirect(['conselho/lista-conselho',
            '   myAlert' => [
                'ty pe' => 'danger',
                'msg    ' => 'Registro não Deletado',
                'redir' => 'index.php?r=conselho/lista-conselho'
                ]
            ]   );
        }
    }
}
?>

controllers/veiculoController.php
<?
namespace app\controllers;

use app\models\CondominioModel;
use app\models\MoradorModel;
use app\models\VeiculoModel;
use Exception;
use yii\web\Controller;
use yii\data\Pagination;
use Yii;
use yii\db\Command;

class VeiculoController extends Controller{
    public function actionListaVeiculo(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }


        $query = (new \yii\db\Query())
        ->select('veic.id,
        veic.idCondominio,
        veic.idMorador,
        cond.nomeCondominio,
        mor.nome,
        veic.placa,
        veic.marca,
        veic.modelo,
        veic.cor,
        veic.vaga,
        veic.tipoVeiculo
        ')
        ->from(VeiculoModel::tableName().' veic')
        ->innerJoin(CondominioModel::tableName().' cond','cond.id = veic.idCondominio')
        ->innerJoin(MoradorModel::tableName().' mor','mor.id = veic.idMorador');



        $paginacao = new Pagination([
            'defaultPageSize'=> 5,
            'totalCount'=> $query->count(),
        ]);

        $veiculo = $query->orderBy('marca')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();

        return $this->render('lista-veiculo', [
            'veiculo'=> $veiculo,
            'paginacao'=>$paginacao,
        ]);
    }

    public function actionFiltroVeiculo(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;

        $query = (new \yii\db\Query())
        ->select('veic.id,
        veic.idCondominio,
        veic.idMorador,
        cond.nomeCondominio,
        mor.nome,
        veic.placa,
        veic.marca,
        veic.modelo,
        veic.cor,
        veic.vaga,
        veic.tipoVeiculo
        ')
        ->from(VeiculoModel::tableName().' veic')
        ->innerJoin(CondominioModel::tableName().' cond','cond.id = veic.idCondominio')
        ->innerJoin(MoradorModel::tableName().' mor','mor.id = veic.idMorador')
        ->where(['like', 'mor.nome', $request->get('termo1')])
        ->andWhere(['like', 'cond.nomeCondominio', $request->get('termo2')]);


        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $veiculo = $query->orderBy('nome')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();


        return $this->render('lista-veiculo',[
            'veiculo'=>$veiculo,
            'paginacao'=>$paginacao,
        ]);
    }

    public static function listaVeiculoSelect(){
        $query = VeiculoModel::find();

        return $query->orderBy('marca')->all();
    }
    public static function listaMoradorSelectEdit($from){
        $query = MoradorModel::find();
        $data = $query->where(['id' => $from])->orderBy('nome')->all();
        return $data;
    }

    public function actionCadastroVeiculo(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        return $this->render('cadastro-veiculo');
    }

    public function actionRealizaCadastroVeiculo(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new VeiculoModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['veiculo/lista-veiculo']);
        }

        return $this->render('cadastro-veiculo');
    }

    public function actionEditarVeiculo(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = VeiculoModel::find();
            $veiculo = $query->where(['id' => $request->get()])->one();
        }
        
        return $this->render('editar-veiculo',[
            'edit' => $veiculo
        ]);
    }
    public function actionRealizaEdicaoVeiculo(){
        $request = \yii::$app->request;
        
        if($request->isPost){
            $model = VeiculoModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            if($model->update()){
                return $this->redirect(['veiculo/lista-veiculo']);
            }else{
                return $this->redirect(['veiculo/lista-veiculo', 'msg' => 'erro']);
            }
        }
    }
    public function actionDeletaVeiculo(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        try {
            $request = \yii::$app->request;
            if($request->isGet){
                $model = VeiculoModel::findOne($request->get('id'));
                if($model->delete()){
                    return $this->redirect(['veiculo/lista-veiculo',
                        'myAlert' => [
                            'type' => 'success',
                            'msg' => 'Registro Deletado',
                            'redir' => 'index.php?r=veiculo/lista-veiculo'
                        ]
                    ]);
                }
                
            } 
        }catch (Exception $th) {         
            return $this->redirect(['veiculo/lista-veiculo',
            'myAlert' => [
                'type' => 'danger',
                'msg' => 'Registro não Deletado',
                'redir' => 'index.php?r=veiculo/lista-veiculo'
                ]
            ]   );
        }
    }
}
?>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Url;


$urlSite = Url::base(true);
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="img/Logo.png" width="100px"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Home', 'url' =>  Yii::$app->homeUrl],
            [
                'label' => 'Listas',
                'items' =>[
                    [
                        'label' => 'Administradora',
                        'url' => ['/administradora/lista-administradora']
                    ],
                    [
                        'label' => 'Condominio',
                        'url' => ['/condominio/lista-condominio']
                    ],
                    [
                        'label' => 'Conselho',
                        'url' => ['conselho/lista-conselho']
                    ],
                    [
                        'label' => 'Bloco',
                        'url' => ['bloco/lista-bloco']
                    ],
                    [
                        'label' => 'Unidade',
                        'url' => ['unidade/lista-unidade']
                    ],
                    [
                        'label' => 'Morador',
                        'url' => ['morador/lista-morador']
                    ],
                    [
                        'label' => 'Veiculo',
                        'url' => ['veiculo/lista-veiculo']
                    ]
                ]
            ],
            [
                'label' => 'Cadastro',
                'items' =>[
                    [
                        'label' => 'Administradora',
                        'url' => ['administradora/cadastro-administradora']
                    ],
                    [
                        'label' => 'Condominio',
                        'url' => ['condominio/cadastro-condominio']
                    ],
                    [
                        'label' => 'Conselho',
                        'url' => ['conselho/cadastro-conselho']
                    ],
                    [
                        'label' => 'Bloco',
                        'url' => ['bloco/cadastro-bloco']
                    ],
                    [
                        'label' => 'Unidade',
                        'url' => ['unidade/cadastro-unidade']
                    ],
                    [
                        'label' => 'Morador',
                        'url' => ['morador/cadastro-morador']
                    ],
                    [
                        'label' => 'Veiculo',
                        'url' => ['veiculo/cadastro-veiculo']
                    ]
                ]
            ],
            Yii::$app -> user -> isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout (' . Yii::$app -> user -> identity -> usuario . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0 mt-5 container">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="container-fluid mt-auto pt-3 text-muted bg-dark">
        <div class="row">
            <div class="col-sm-4">
                <p class="float-left text-light">&copy; todos os direitos reservados <?= date('Y') ?></p>
            </div>
            <div class="col-sm-4 text-center">
                <a href="https://api.whatsapp.com/send?phone=+5547991594765"><i class="bi bi-whatsapp text-light"> Suporte</i></a>
            </div>
            <div class="col-sm-4">
                <p class="float-right text-light"><?= Yii::powered() ?></p>
            </div>
        </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>