controllers/unidadeController.php
<?
namespace app\controllers;

use app\models\BlocoModel;
use app\models\CondominioModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\UnidadeModel;
use Yii;

class UnidadeController extends Controller{
    public function actionListaUnidade(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }


        $query = (new \yii\db\Query())
        ->select('unid.id,
        cond.id,
        b.id,
        cond.nomeCondominio,
        b.nomeBloco,
        unid.numero,
        unid.metragem,
        unid.qtVagas
        ')
        ->from(UnidadeModel::tableName().' unid')
        ->innerJoin(CondominioModel::tableName().' cond','cond.id = unid.idCondominio')
        ->innerJoin(BlocoModel::tableName().' b','b.id = unid.idBloco');

        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $unidade = $query->orderBy('numero')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();


        return $this->render('lista-unidade',[
            'unidade'=>$unidade,
            'paginacao'=>$paginacao,
        ]);
    }

    public function actionFiltroUnidade(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $request = \yii::$app->request;

        $query = (new \yii\db\Query())
        ->select('
        unid.id,
        cond.id,
        b.id,
        cond.nomeCondominio,
        b.nomeBloco,
        unid.numero,
        unid.metragem,
        unid.qtVagas
        ')
        ->from(UnidadeModel::tableName().' unid')
        ->innerJoin(CondominioModel::tableName().' cond','cond.id = unid.idCondominio')
        ->innerJoin(BlocoModel::tableName().' b', 'b.id = unid.idBloco')
        ->where(['like', 'unid.numero', $request->get('termo1')])
        ->andWhere(['like', 'cond.nomeCondominio', $request->get('termo2')]);


        $paginacao = new Pagination([
            'defaultPageSize'=>5,
            'totalCount'=>$query->count(),
        ]);

        $unidade = $query->orderBy('numero')
        ->offset($paginacao->offset)
        ->limit($paginacao->limit)
        ->all();


        return $this->render('lista-unidade',[
            'unidade'=>$unidade,
            'paginacao'=>$paginacao,
        ]);
    }

    public static function listaUnidadeSelect(){
        $query = UnidadeModel::find();

        return $query->orderBy('numero')->all();
    }
    public static function listaUnidadeSelectEdit($from){
        $query = UnidadeModel::find();
        $data = $query->where(['idBloco' => $from])->orderBy('numero')->all();
        return $data;
    }

    public function actionCadastroUnidade(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        return $this->render('cadastro-unidade');
    }

    public function actionRealizaCadastroUnidade(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new UnidadeModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['unidade/cadastro-unidade']);
        }

        return $this->render('cadastro-unidade');
    }
    public function actionListaUnidadeApi(){
        $request = \yii::$app->request;
        $query = UnidadeModel::find();
        $data = $query->where(['idBloco' => $request->post()])->orderBy('numero')->all();

        $dados = array();
        $i=0;
        foreach($data as $d){
        $dados[$i]['id'] = $d['id'];
        $dados[$i]['numero'] = $d['numero'];
        $i++;
        }
        echo json_encode($dados);

        
    }
    public function actionEditarUnidade(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = UnidadeModel::find();
            $unidade = $query->where(['id' => $request->get()])->one();
        }
        
        return $this->render('editar-unidade',[
            'edit' => $unidade
        ]);
    }
    public function actionRealizaEdicaoUnidade(){
        $request = \yii::$app->request;
        
        if($request->isPost){
            $model = UnidadeModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            if($model->update()){
                return $this->redirect(['unidade/lista-unidade']);
            }else{
                return $this->redirect(['unidade/lista-unidade', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaUnidade(){
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        try {
            $request = \yii::$app->request;
            if($request->isGet){
                $model = BlocoModel::findOne($request->get('id'));
                if($model->delete()){
                    return $this->redirect(['unidade/lista-unidade',
                        'myAlert' => [
                            'type' => 'success',
                            'msg' => 'Registro Deletado',
                            'redir' => 'unidade/lista-unidade'
                        ]
                    ]);
                }
                
            } 
        }catch (\Throwable $th) {         
            return $this->redirect(['unidade/lista-unidade',
            '   myAlert' => [
                'ty pe' => 'danger',
                'msg    ' => 'Registro não Deletado',
                'redir' => 'unidade/lista-unidade'
                ]
            ]   );
        }
    }
}
?>

views/unidade/cadastro-unidade.php
<?
use app\controllers\CondominioController;
use yii\helpers\Url;
?>
<h1 class="text-center mb-5 text-light">Cadastro de Unidade</h1>
<form action="<?=Url::to(['unidade/realiza-cadastro-unidade'])?>" class="formUnidade" method="POST">
  <div class="form-row">
  <div class="form-group col-md-3">
        <select id="inputState" class="fromCondominio form-control" name="idCondominio">
          <option>Selecione...</option>
        <?foreach(CondominioController::listaCondominioSelect() as $condo){?>
          <option value="<?=$condo['id']?>" ><?=$condo['nomeCondominio']?></option>
          <?}?>
        </select>
      </div>
    <div class="form-group col-md-3">
        <select id="inputState" class="fromBloco form-control" name="idBloco">
        
        </select>
      </div>
      <div class="form-group col-md-2">
        <input type="text" class="form-control" name="numero" value="" placeholder="numero">
      </div>
    <div class="form-group col-md-2">
      <input type="text" class="form-control" name="metragem" value="" placeholder="metragem">
    </div>
    <div class="form-group col-md-2">
      <input type="text" class="form-control" name="qtVagas" value="" placeholder="Vagas Garagem">
    </div>
  </div>
  <div class="form-group">
            <input type="hidden" name="<?=\yii::$app->request->csrfParam; ?>" value="<?=\yii::$app->request->csrfToken;?>">
    </div>
  <button type="submit" class="btn btn-primary buttonEnviar">Enviar</button>
</form>

views/unidade/editar-unidade.php
<?

use app\components\selectedComponent;
use app\controllers\BlocoController;
use app\controllers\CondominioController;
use yii\helpers\Url;
?>

<form action="<?=Url::to(['unidade/realiza-edicao-unidade'])?>" class="formUnidade" method="POST">
  <div class="form-row">
  <div class="form-group col-md-3">
        <select id="inputState" class="fromCondominio form-control" name="idCondominio">
          <option>Selecione...</option>
        <?foreach(CondominioController::listaCondominioSelect() as $condo){?>
          <option value="<?=$condo['id']?>" <?=selectedComponent::isSelected($condo['id'],$edit['idCondominio'])?>><?=$condo['nomeCondominio']?></option>
          <?}?>
        </select>
      </div>
    <div class="form-group col-md-3">
    <select id="inputState" class="fromBloco form-control" name="idBloco">
            <option value="">Selecione...</option>
            
        <?foreach(BlocoController::listaBlocoSelectEdit($edit['idCondominio']) as $bloco){?>
            <option value="<?=$bloco['id']?>" <?=selectedComponent::isSelected($bloco['id'],$edit['idBloco'])?>><?=$bloco['nomeBloco']?></option>
          <?}?>
        </select>
      </div>
      <div class="form-group col-md-2">
        <input type="text" class="form-control" name="numero" value="<?=$edit['numero']?>" placeholder="numero">
      </div>
    <div class="form-group col-md-2">
      <input type="text" class="form-control" name="metragem" value="<?=$edit['metragem']?>" placeholder="metragem">
    </div>
    <div class="form-group col-md-2">
      <input type="text" class="form-control" name="qtVagas" value="<?=$edit['qtVagas']?>" placeholder="Vagas Garagem">
    </div>
  </div>
  <div class="form-group">
    <input type="hidden" name="id" value="<?=$edit['id']?>">
    <input type="hidden" name="<?=\yii::$app->request->csrfParam; ?>" value="<?=\yii::$app->request->csrfToken;?>">
  </div>
  <button type="submit" class="btn btn-primary buttonEnviar">Enviar</button>
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
</form>

views/unidade/lista-unidade.php
<?

use app\components\alertComponent;
use app\components\filtroComponent;
use app\components\modalComponent;
use app\controllers\CondominioController;
use yii\helpers\Html;
use yii\widgets\LinkPager;

global $urlSite;
if(isset($_GET['myAlert'])){

    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}
?>
<h1 class="text-center">Lista Unidade</h1>
<table class="table table-striped table-hover table-bordered table-dark" id="listaUnidade">
    <tr>
            <td colspan="10">
            <?=filtroComponent::filtro('unidade','filtro-unidade','numero','condominio',CondominioController::listaCondominioSelect(), 'nomeCondominio')?>
            </td>
        </tr>
        <tr>
            <td scope="col" class="text-center">Condominio</td>
            <td scope="col" class="text-center">Bloco</td>
            <td scope="col" class="text-center">numero</td>
            <td scope="col" class="text-center">Metragem</td>
            <td scope="col" class="text-center">qt Vagas na Garagem</td>
            <td class="text-center"><a href="<?=$urlSite?>?r=unidade/cadastro-unidade" class="btn btn-light px-3 py-0"><small class="mr-2">Adicionar</small><i class="bi bi-plus-circle"></i></a></td>
        </tr>
        <?     
        foreach($unidade as $ch2=>$dados){
        ?>
        <tr data-id="<?=$dados['id']?>">
            <td class="text-center"><?=$dados['nomeCondominio']?></td>
            <td class="text-center"><?=$dados['nomeBloco']?></td>
            <td class="text-center"><?=$dados['numero']?></td>
            <td class="text-center"><?=$dados['metragem']?></td>
            <td class="text-center"><?=$dados['qtVagas']?></td>
            <td class="text-center">
                <a href="<?=$urlSite?>?r=unidade/deleta-unidade&id=<?=$dados['id']?>" data-id="<?=$dados['id']?>" class="removerUnidade text-white mr-5"><i class="bi bi-trash3"></i></a>
                <a href="<?=$urlSite?>?r=unidade/editar-unidade&id=<?=$dados['id']?>" class=" text-white openModal"><i class="bi bi-pencil-square"></i></a>
            </td>
        </tr>
        <? } ?>
        <tr>
            <td colspan="10" class="text-right">Total Registros <small class="badge badge-light totalRegistro"><?=$paginacao->totalCount?></small></td>
        </tr>
     </table> 
     <div class="row">
    <div class="col-md-12 mb-5">
        <?= LinkPager::widget(
            [
                'pagination' => $paginacao,
                'linkContainerOptions' =>[
                    'class' => 'page-item'
                ],
                'linkOptions' => [
                    'class' => 'page-link'
                ],
                'disabledListItemSubTagOptions' => [
                    'class' => 'page-link'
                ]
                ]) 
        ?>
    </div>
</div>
<?=modalComponent::modal()?>